[2025-08-05T15:51:27.639+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Ejercicio1.LoadAndSetdimproduct manual__2025-08-05T15:50:49.879368+00:00 [queued]>
[2025-08-05T15:51:27.670+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Ejercicio1.LoadAndSetdimproduct manual__2025-08-05T15:50:49.879368+00:00 [queued]>
[2025-08-05T15:51:27.672+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-08-05T15:51:27.730+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): LoadAndSetdimproduct> on 2025-08-05 15:50:49.879368+00:00
[2025-08-05T15:51:27.751+0000] {standard_task_runner.py:60} INFO - Started process 220 to run task
[2025-08-05T15:51:27.761+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'Ejercicio1', 'LoadAndSetdimproduct', 'manual__2025-08-05T15:50:49.879368+00:00', '--job-id', '83', '--raw', '--subdir', 'DAGS_FOLDER/ejercicio1.py', '--cfg-path', '/tmp/tmpfq0d26cv']
[2025-08-05T15:51:27.772+0000] {standard_task_runner.py:88} INFO - Job 83: Subtask LoadAndSetdimproduct
[2025-08-05T15:51:27.971+0000] {task_command.py:423} INFO - Running <TaskInstance: Ejercicio1.LoadAndSetdimproduct manual__2025-08-05T15:50:49.879368+00:00 [running]> on host 019b67754667
[2025-08-05T15:51:28.293+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Ejercicio1' AIRFLOW_CTX_TASK_ID='LoadAndSetdimproduct' AIRFLOW_CTX_EXECUTION_DATE='2025-08-05T15:50:49.879368+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-05T15:50:49.879368+00:00'
[2025-08-05T15:51:28.999+0000] {_client.py:1038} INFO - HTTP Request: GET https://qwpzsjaaxuijmqodvslf.supabase.co/rest/v1/dimproduct?select=%2A "HTTP/2 200 OK"
[2025-08-05T15:51:28.694+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ejercicio1.py", line 116, in call
    get_inactive(table, cond,engine)
  File "/opt/airflow/dags/ejercicio1.py", line 42, in get_inactive
    comparison = df.merge(df_customers,on=[id],how='outer',indicator=True,suffixes=('_PG', '_SP'))
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/frame.py", line 9843, in merge
    return merge(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/reshape/merge.py", line 148, in merge
    op = _MergeOperation(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/reshape/merge.py", line 737, in __init__
    ) = self._get_merge_keys()
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/reshape/merge.py", line 1203, in _get_merge_keys
    right_keys.append(right._get_label_or_level_values(rk))
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 1778, in _get_label_or_level_values
    raise KeyError(key)
KeyError: 'productid'
[2025-08-05T15:51:28.818+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=Ejercicio1, task_id=LoadAndSetdimproduct, execution_date=20250805T155049, start_date=20250805T155127, end_date=20250805T155128
[2025-08-05T15:51:28.860+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 83 for task LoadAndSetdimproduct ('productid'; 220)
[2025-08-05T15:51:28.900+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-08-05T15:51:28.103+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
