[2025-08-05T22:12:19.459+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Ejercicio1.Inicio manual__2025-08-05T22:12:05.944049+00:00 [queued]>
[2025-08-05T22:12:19.483+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Ejercicio1.Inicio manual__2025-08-05T22:12:05.944049+00:00 [queued]>
[2025-08-05T22:12:19.486+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-08-05T22:12:19.520+0000] {taskinstance.py:2191} INFO - Executing <Task(BranchPythonOperator): Inicio> on 2025-08-05 22:12:05.944049+00:00
[2025-08-05T22:12:19.554+0000] {standard_task_runner.py:60} INFO - Started process 2071 to run task
[2025-08-05T22:12:19.561+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'Ejercicio1', 'Inicio', 'manual__2025-08-05T22:12:05.944049+00:00', '--job-id', '180', '--raw', '--subdir', 'DAGS_FOLDER/ejercicio1.py', '--cfg-path', '/tmp/tmpl0rbfj78']
[2025-08-05T22:12:19.566+0000] {standard_task_runner.py:88} INFO - Job 180: Subtask Inicio
[2025-08-05T22:12:19.691+0000] {task_command.py:423} INFO - Running <TaskInstance: Ejercicio1.Inicio manual__2025-08-05T22:12:05.944049+00:00 [running]> on host 019b67754667
[2025-08-05T22:12:19.884+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Ejercicio1' AIRFLOW_CTX_TASK_ID='Inicio' AIRFLOW_CTX_EXECUTION_DATE='2025-08-05T22:12:05.944049+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-05T22:12:05.944049+00:00'
[2025-08-05T22:12:20.679+0000] {logging_mixin.py:188} INFO - -------------------------TABLES------------------
[2025-08-05T22:12:20.681+0000] {logging_mixin.py:188} INFO - NO HAY TABLAS
[2025-08-05T22:12:20.682+0000] {python.py:201} INFO - Done. Returned value was: CrearTablasCsv
[2025-08-05T22:12:20.683+0000] {branch.py:35} INFO - Branch into CrearTablasCsv
[2025-08-05T22:12:20.685+0000] {skipmixin.py:178} INFO - Following branch CrearTablasCsv
[2025-08-05T22:12:20.704+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 233, in execute
    return self.do_branch(context, super().execute(context))
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/branch.py", line 36, in do_branch
    self.skip_all_except(context["ti"], branches_to_execute)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/skipmixin.py", line 213, in skip_all_except
    raise AirflowException(
airflow.exceptions.AirflowException: 'branch_task_ids' must contain only valid task_ids. Invalid tasks found: {'CrearTablasCsv'}.
[2025-08-05T22:12:21.018+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=Ejercicio1, task_id=Inicio, execution_date=20250805T221205, start_date=20250805T221219, end_date=20250805T221221
[2025-08-05T22:12:21.615+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 180 for task Inicio ('branch_task_ids' must contain only valid task_ids. Invalid tasks found: {'CrearTablasCsv'}.; 2071)
[2025-08-05T22:12:21.763+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-08-05T22:12:21.845+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
