[2025-08-05T15:45:06.893+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Ejercicio1.LoadAndSetdimdate manual__2025-08-05T02:23:41.610397+00:00 [queued]>
[2025-08-05T15:45:06.944+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Ejercicio1.LoadAndSetdimdate manual__2025-08-05T02:23:41.610397+00:00 [queued]>
[2025-08-05T15:45:06.956+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 2
[2025-08-05T15:45:07.064+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): LoadAndSetdimdate> on 2025-08-05 02:23:41.610397+00:00
[2025-08-05T15:45:07.110+0000] {standard_task_runner.py:60} INFO - Started process 118 to run task
[2025-08-05T15:45:07.151+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'Ejercicio1', 'LoadAndSetdimdate', 'manual__2025-08-05T02:23:41.610397+00:00', '--job-id', '76', '--raw', '--subdir', 'DAGS_FOLDER/ejercicio1.py', '--cfg-path', '/tmp/tmpzsdl754s']
[2025-08-05T15:45:07.200+0000] {standard_task_runner.py:88} INFO - Job 76: Subtask LoadAndSetdimdate
[2025-08-05T15:45:07.410+0000] {task_command.py:423} INFO - Running <TaskInstance: Ejercicio1.LoadAndSetdimdate manual__2025-08-05T02:23:41.610397+00:00 [running]> on host 019b67754667
[2025-08-05T15:45:07.806+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Ejercicio1' AIRFLOW_CTX_TASK_ID='LoadAndSetdimdate' AIRFLOW_CTX_EXECUTION_DATE='2025-08-05T02:23:41.610397+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-05T02:23:41.610397+00:00'
[2025-08-05T15:45:10.517+0000] {_client.py:1038} INFO - HTTP Request: GET https://qwpzsjaaxuijmqodvslf.supabase.co/rest/v1/StgLogs?select=%2A "HTTP/2 200 OK"
[2025-08-05T15:45:12.195+0000] {_client.py:1038} INFO - HTTP Request: GET https://qwpzsjaaxuijmqodvslf.supabase.co/rest/v1/StgLogs?select=last_id&table_name=eq.dimdate "HTTP/2 200 OK"
[2025-08-05T15:45:12.203+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ejercicio1.py", line 114, in call
    set_lastid(table, cond,engine)
  File "/opt/airflow/dags/ejercicio1.py", line 96, in set_lastid
    last_id = result.data[0].get('last_id')
IndexError: list index out of range
[2025-08-05T15:45:12.772+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=Ejercicio1, task_id=LoadAndSetdimdate, execution_date=20250805T022341, start_date=20250805T154506, end_date=20250805T154512
[2025-08-05T15:45:12.871+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 76 for task LoadAndSetdimdate (list index out of range; 118)
[2025-08-05T15:45:12.933+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-08-05T15:45:13.036+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
