[2025-08-05T22:15:08.118+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Ejercicio1.CreaTabladimcustomersegment manual__2025-08-05T22:14:41.245898+00:00 [queued]>
[2025-08-05T22:15:08.175+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Ejercicio1.CreaTabladimcustomersegment manual__2025-08-05T22:14:41.245898+00:00 [queued]>
[2025-08-05T22:15:08.177+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-08-05T22:15:08.242+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): CreaTabladimcustomersegment> on 2025-08-05 22:14:41.245898+00:00
[2025-08-05T22:15:08.325+0000] {standard_task_runner.py:60} INFO - Started process 2130 to run task
[2025-08-05T22:15:08.353+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'Ejercicio1', 'CreaTabladimcustomersegment', 'manual__2025-08-05T22:14:41.245898+00:00', '--job-id', '185', '--raw', '--subdir', 'DAGS_FOLDER/ejercicio1.py', '--cfg-path', '/tmp/tmpa1e0_xlg']
[2025-08-05T22:15:08.381+0000] {standard_task_runner.py:88} INFO - Job 185: Subtask CreaTabladimcustomersegment
[2025-08-05T22:15:08.749+0000] {task_command.py:423} INFO - Running <TaskInstance: Ejercicio1.CreaTabladimcustomersegment manual__2025-08-05T22:14:41.245898+00:00 [running]> on host 019b67754667
[2025-08-05T22:15:09.446+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Ejercicio1' AIRFLOW_CTX_TASK_ID='CreaTabladimcustomersegment' AIRFLOW_CTX_EXECUTION_DATE='2025-08-05T22:14:41.245898+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-05T22:14:41.245898+00:00'
[2025-08-05T22:15:09.904+0000] {logging_mixin.py:188} INFO - 
 --------------DB
     segmentid            city
0          19       Sao Paulo
1          21       Sao Paulo
2          31  Rio de Janeiro
3          32  Rio de Janeiro
4          40        Brasilia
5          43        Brasilia
6          44  Rio de Janeiro
7          46        Brasilia
8          47        Salvador
9          48        Salvador
10         57  Rio de Janeiro
11         71        Brasilia
12         77        Brasilia
13         81        Salvador
14         82        Salvador
15         83       Sao Paulo
16         84  Rio de Janeiro
17         86  Rio de Janeiro
18         97        Brasilia 
 --------------
[2025-08-05T22:15:12.683+0000] {_client.py:1038} INFO - HTTP Request: POST https://qwpzsjaaxuijmqodvslf.supabase.co/rest/v1/StgCustomer?columns=%22state%22%2C%22segmentid%22%2C%22city%22 "HTTP/2 400 Bad Request"
[2025-08-05T22:15:12.694+0000] {logging_mixin.py:188} INFO - Error insertando en StgCustomer: {'code': 'PGRST204', 'details': None, 'hint': None, 'message': "Could not find the 'city' column of 'StgCustomer' in the schema cache"}
[2025-08-05T22:15:12.963+0000] {_client.py:1038} INFO - HTTP Request: POST https://qwpzsjaaxuijmqodvslf.supabase.co/rest/v1/StgCustomer?columns=%22state%22%2C%22segmentid%22%2C%22city%22 "HTTP/2 400 Bad Request"
[2025-08-05T22:15:12.970+0000] {logging_mixin.py:188} INFO - Error insertando en StgCustomer: {'code': 'PGRST204', 'details': None, 'hint': None, 'message': "Could not find the 'city' column of 'StgCustomer' in the schema cache"}
[2025-08-05T22:15:13.836+0000] {_client.py:1038} INFO - HTTP Request: POST https://qwpzsjaaxuijmqodvslf.supabase.co/rest/v1/dimcustomersegment?columns=%22segmentid%22%2C%22city%22 "HTTP/2 201 Created"
[2025-08-05T22:15:13.898+0000] {logging_mixin.py:188} INFO - ---------------------------------------Datos insertados Correctamente dimcustomersegment------------------------
 
[2025-08-05T22:15:14.160+0000] {_client.py:1038} INFO - HTTP Request: POST https://qwpzsjaaxuijmqodvslf.supabase.co/rest/v1/dimcustomersegment?columns=%22segmentid%22%2C%22city%22 "HTTP/2 201 Created"
[2025-08-05T22:15:14.165+0000] {logging_mixin.py:188} INFO - ---------------------------------------Datos insertados Correctamente dimcustomersegment------------------------
 
[2025-08-05T22:15:14.944+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ejercicio1.py", line 105, in call
    set_inactive(table,id,engine)
  File "/opt/airflow/dags/ejercicio1.py", line 81, in set_inactive
    set_lastid_logs(table, last_id_supabase)
  File "/opt/airflow/dags/ejercicio1.py", line 68, in set_lastid_logs
    supabase.table("StgLogs").update({
  File "/home/airflow/.local/lib/python3.8/site-packages/postgrest/_sync/request_builder.py", line 58, in execute
    r = self.session.request(
  File "/home/airflow/.local/lib/python3.8/site-packages/httpx/_client.py", line 824, in request
    request = self.build_request(
  File "/home/airflow/.local/lib/python3.8/site-packages/httpx/_client.py", line 358, in build_request
    return Request(
  File "/home/airflow/.local/lib/python3.8/site-packages/httpx/_models.py", line 342, in __init__
    headers, stream = encode_request(
  File "/home/airflow/.local/lib/python3.8/site-packages/httpx/_content.py", line 214, in encode_request
    return encode_json(json)
  File "/home/airflow/.local/lib/python3.8/site-packages/httpx/_content.py", line 177, in encode_json
    body = json_dumps(json).encode("utf-8")
  File "/usr/local/lib/python3.8/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type int64 is not JSON serializable
[2025-08-05T22:15:15.149+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=Ejercicio1, task_id=CreaTabladimcustomersegment, execution_date=20250805T221441, start_date=20250805T221508, end_date=20250805T221515
[2025-08-05T22:15:15.334+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 185 for task CreaTabladimcustomersegment (Object of type int64 is not JSON serializable; 2130)
[2025-08-05T22:15:15.466+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-08-05T22:15:18.291+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
