[2025-08-05T19:09:54.385+0000] {scheduler_job_runner.py:781} ERROR - Executor reports task instance <TaskInstance: Ejercicio1.LoadAndSetdimproduct manual__2025-08-05T19:04:30.609150+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
