[2025-08-05T19:04:49.696+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Ejercicio1.LoadAndSetdimproduct manual__2025-08-05T19:04:30.609150+00:00 [queued]>
[2025-08-05T19:04:49.729+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Ejercicio1.LoadAndSetdimproduct manual__2025-08-05T19:04:30.609150+00:00 [queued]>
[2025-08-05T19:04:49.731+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-08-05T19:04:50.070+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): LoadAndSetdimproduct> on 2025-08-05 19:04:30.609150+00:00
[2025-08-05T19:04:50.256+0000] {standard_task_runner.py:60} INFO - Started process 699 to run task
[2025-08-05T19:04:50.271+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'Ejercicio1', 'LoadAndSetdimproduct', 'manual__2025-08-05T19:04:30.609150+00:00', '--job-id', '106', '--raw', '--subdir', 'DAGS_FOLDER/ejercicio1.py', '--cfg-path', '/tmp/tmptr75z3n_']
[2025-08-05T19:04:50.319+0000] {standard_task_runner.py:88} INFO - Job 106: Subtask LoadAndSetdimproduct
[2025-08-05T19:04:50.546+0000] {task_command.py:423} INFO - Running <TaskInstance: Ejercicio1.LoadAndSetdimproduct manual__2025-08-05T19:04:30.609150+00:00 [running]> on host 019b67754667
[2025-08-05T19:04:50.917+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Ejercicio1' AIRFLOW_CTX_TASK_ID='LoadAndSetdimproduct' AIRFLOW_CTX_EXECUTION_DATE='2025-08-05T19:04:30.609150+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-05T19:04:30.609150+00:00'
[2025-08-05T19:04:50.981+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3653, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 147, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 176, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 7080, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 7088, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'productid'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ejercicio1.py", line 108, in call
    set_lastid(table, cond,engine)
  File "/opt/airflow/dags/ejercicio1.py", line 93, in set_lastid
    last_id = df[cond].max()
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/frame.py", line 3761, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3655, in get_loc
    raise KeyError(key) from err
KeyError: 'productid'
[2025-08-05T19:04:51.404+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=Ejercicio1, task_id=LoadAndSetdimproduct, execution_date=20250805T190430, start_date=20250805T190449, end_date=20250805T190451
[2025-08-05T19:04:51.640+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 106 for task LoadAndSetdimproduct ('productid'; 699)
[2025-08-05T19:04:52.483+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-08-05T19:04:52.565+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
