[2025-08-06T22:47:34.542+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Ejercicio2.Inicio manual__2025-08-06T22:41:45.567748+00:00 [queued]>
[2025-08-06T22:47:34.577+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Ejercicio2.Inicio manual__2025-08-06T22:41:45.567748+00:00 [queued]>
[2025-08-06T22:47:34.579+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 2
[2025-08-06T22:47:34.629+0000] {taskinstance.py:2191} INFO - Executing <Task(BranchPythonOperator): Inicio> on 2025-08-06 22:41:45.567748+00:00
[2025-08-06T22:47:34.648+0000] {standard_task_runner.py:60} INFO - Started process 4173 to run task
[2025-08-06T22:47:34.660+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'Ejercicio2', 'Inicio', 'manual__2025-08-06T22:41:45.567748+00:00', '--job-id', '268', '--raw', '--subdir', 'DAGS_FOLDER/ejercicio2.py', '--cfg-path', '/tmp/tmp37579cqd']
[2025-08-06T22:47:34.664+0000] {standard_task_runner.py:88} INFO - Job 268: Subtask Inicio
[2025-08-06T22:47:34.849+0000] {task_command.py:423} INFO - Running <TaskInstance: Ejercicio2.Inicio manual__2025-08-06T22:41:45.567748+00:00 [running]> on host 019b67754667
[2025-08-06T22:47:35.114+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Ejercicio2' AIRFLOW_CTX_TASK_ID='Inicio' AIRFLOW_CTX_EXECUTION_DATE='2025-08-06T22:41:45.567748+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-06T22:41:45.567748+00:00'
[2025-08-06T22:47:35.118+0000] {logging_mixin.py:188} INFO - HOLA
[2025-08-06T22:47:35.120+0000] {python.py:201} INFO - Done. Returned value was: cargainicial
[2025-08-06T22:47:35.123+0000] {branch.py:35} INFO - Branch into cargainicial
[2025-08-06T22:47:35.125+0000] {skipmixin.py:178} INFO - Following branch cargainicial
[2025-08-06T22:47:35.158+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 233, in execute
    return self.do_branch(context, super().execute(context))
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/branch.py", line 36, in do_branch
    self.skip_all_except(context["ti"], branches_to_execute)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/skipmixin.py", line 213, in skip_all_except
    raise AirflowException(
airflow.exceptions.AirflowException: 'branch_task_ids' must contain only valid task_ids. Invalid tasks found: {'cargainicial'}.
[2025-08-06T22:47:35.170+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=Ejercicio2, task_id=Inicio, execution_date=20250806T224145, start_date=20250806T224734, end_date=20250806T224735
[2025-08-06T22:47:35.215+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 268 for task Inicio ('branch_task_ids' must contain only valid task_ids. Invalid tasks found: {'cargainicial'}.; 4173)
[2025-08-06T22:47:35.276+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-08-06T22:47:35.344+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
