[2025-08-06T22:47:34.978+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Ejercicio2.Inicio scheduled__2025-07-28T00:00:00+00:00 [queued]>
[2025-08-06T22:47:35.012+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Ejercicio2.Inicio scheduled__2025-07-28T00:00:00+00:00 [queued]>
[2025-08-06T22:47:35.014+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 2
[2025-08-06T22:47:35.058+0000] {taskinstance.py:2191} INFO - Executing <Task(BranchPythonOperator): Inicio> on 2025-07-28 00:00:00+00:00
[2025-08-06T22:47:35.083+0000] {standard_task_runner.py:60} INFO - Started process 4174 to run task
[2025-08-06T22:47:35.097+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'Ejercicio2', 'Inicio', 'scheduled__2025-07-28T00:00:00+00:00', '--job-id', '269', '--raw', '--subdir', 'DAGS_FOLDER/ejercicio2.py', '--cfg-path', '/tmp/tmpc5tzwrye']
[2025-08-06T22:47:35.102+0000] {standard_task_runner.py:88} INFO - Job 269: Subtask Inicio
[2025-08-06T22:47:35.280+0000] {task_command.py:423} INFO - Running <TaskInstance: Ejercicio2.Inicio scheduled__2025-07-28T00:00:00+00:00 [running]> on host 019b67754667
[2025-08-06T22:47:35.573+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Ejercicio2' AIRFLOW_CTX_TASK_ID='Inicio' AIRFLOW_CTX_EXECUTION_DATE='2025-07-28T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-07-28T00:00:00+00:00'
[2025-08-06T22:47:35.577+0000] {logging_mixin.py:188} INFO - HOLA
[2025-08-06T22:47:35.579+0000] {python.py:201} INFO - Done. Returned value was: cargainicial
[2025-08-06T22:47:35.585+0000] {branch.py:35} INFO - Branch into cargainicial
[2025-08-06T22:47:35.587+0000] {skipmixin.py:178} INFO - Following branch cargainicial
[2025-08-06T22:47:35.631+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 233, in execute
    return self.do_branch(context, super().execute(context))
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/branch.py", line 36, in do_branch
    self.skip_all_except(context["ti"], branches_to_execute)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/skipmixin.py", line 213, in skip_all_except
    raise AirflowException(
airflow.exceptions.AirflowException: 'branch_task_ids' must contain only valid task_ids. Invalid tasks found: {'cargainicial'}.
[2025-08-06T22:47:35.646+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=Ejercicio2, task_id=Inicio, execution_date=20250728T000000, start_date=20250806T224734, end_date=20250806T224735
[2025-08-06T22:47:35.695+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 269 for task Inicio ('branch_task_ids' must contain only valid task_ids. Invalid tasks found: {'cargainicial'}.; 4174)
[2025-08-06T22:47:35.753+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-08-06T22:47:35.830+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
