[2025-08-05T19:12:20.032+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Ejercicio1.LoadAndSetdimproduct manual__2025-08-05T19:11:50.986885+00:00 [queued]>
[2025-08-05T19:12:20.176+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Ejercicio1.LoadAndSetdimproduct manual__2025-08-05T19:11:50.986885+00:00 [queued]>
[2025-08-05T19:12:20.178+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-08-05T19:12:21.034+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): LoadAndSetdimproduct> on 2025-08-05 19:11:50.986885+00:00
[2025-08-05T19:12:21.049+0000] {standard_task_runner.py:60} INFO - Started process 821 to run task
[2025-08-05T19:12:21.055+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'Ejercicio1', 'LoadAndSetdimproduct', 'manual__2025-08-05T19:11:50.986885+00:00', '--job-id', '115', '--raw', '--subdir', 'DAGS_FOLDER/ejercicio1.py', '--cfg-path', '/tmp/tmpzeb7kjc7']
[2025-08-05T19:12:21.059+0000] {standard_task_runner.py:88} INFO - Job 115: Subtask LoadAndSetdimproduct
[2025-08-05T19:12:22.523+0000] {task_command.py:423} INFO - Running <TaskInstance: Ejercicio1.LoadAndSetdimproduct manual__2025-08-05T19:11:50.986885+00:00 [running]> on host 019b67754667
[2025-08-05T19:12:23.254+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Ejercicio1' AIRFLOW_CTX_TASK_ID='LoadAndSetdimproduct' AIRFLOW_CTX_EXECUTION_DATE='2025-08-05T19:11:50.986885+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-05T19:11:50.986885+00:00'
[2025-08-05T19:12:23.534+0000] {logging_mixin.py:188} INFO -     Productid   Producttype
0        1001   Electronics
1        1002      Clothing
2        1003     Furniture
3        1004     Groceries
4        1005    Appliances
5        1006        Beauty
6        1007         Books
7        1008         Shoes
8        1009     Gardening
9        1010        Sports
10       1011          Toys
11       1012       Jewelry
12       1013         Tools
13       1014   Kitchenware
14       1015  Pet Supplies
15       1016  Art Supplies
16       1017   Electronics
17       1018      Clothing
18       1019     Furniture
19       1020     Groceries
20       1021    Appliances
21       1022        Beauty
22       1023         Books
23       1024         Shoes
24       1025     Gardening
[2025-08-05T19:12:23.540+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3653, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 147, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 176, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 7080, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 7088, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'productid'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ejercicio1.py", line 112, in call
    set_lastid(table, cond,engine)
  File "/opt/airflow/dags/ejercicio1.py", line 97, in set_lastid
    last_id = df[cond].max()
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/frame.py", line 3761, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3655, in get_loc
    raise KeyError(key) from err
KeyError: 'productid'
[2025-08-05T19:12:23.854+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=Ejercicio1, task_id=LoadAndSetdimproduct, execution_date=20250805T191150, start_date=20250805T191220, end_date=20250805T191223
[2025-08-05T19:12:23.961+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 115 for task LoadAndSetdimproduct ('productid'; 821)
[2025-08-05T19:12:24.076+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-08-05T19:12:24.251+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
