[2025-08-07T01:51:41.760+0000] {scheduler_job_runner.py:781} ERROR - Executor reports task instance <TaskInstance: Ejercicio2.cargaincremental manual__2025-08-07T01:51:34.249172+00:00 [queued]> finished (success) although the task says it's queued. (Info: None) Was the task killed externally?
