[2025-08-06T23:26:51.456+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Ejercicio2.Inicio manual__2025-08-06T23:26:45.739150+00:00 [queued]>
[2025-08-06T23:26:51.487+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Ejercicio2.Inicio manual__2025-08-06T23:26:45.739150+00:00 [queued]>
[2025-08-06T23:26:51.489+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-08-06T23:26:51.540+0000] {taskinstance.py:2191} INFO - Executing <Task(BranchPythonOperator): Inicio> on 2025-08-06 23:26:45.739150+00:00
[2025-08-06T23:26:51.562+0000] {standard_task_runner.py:60} INFO - Started process 4727 to run task
[2025-08-06T23:26:51.575+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'Ejercicio2', 'Inicio', 'manual__2025-08-06T23:26:45.739150+00:00', '--job-id', '285', '--raw', '--subdir', 'DAGS_FOLDER/ejercicio2.py', '--cfg-path', '/tmp/tmpeq32d1oo']
[2025-08-06T23:26:51.694+0000] {standard_task_runner.py:88} INFO - Job 285: Subtask Inicio
[2025-08-06T23:26:52.514+0000] {task_command.py:423} INFO - Running <TaskInstance: Ejercicio2.Inicio manual__2025-08-06T23:26:45.739150+00:00 [running]> on host 019b67754667
[2025-08-06T23:26:53.066+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Ejercicio2' AIRFLOW_CTX_TASK_ID='Inicio' AIRFLOW_CTX_EXECUTION_DATE='2025-08-06T23:26:45.739150+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-06T23:26:45.739150+00:00'
[2025-08-06T23:26:54.222+0000] {_client.py:1038} INFO - HTTP Request: GET https://qwpzsjaaxuijmqodvslf.supabase.co/rest/v1/cotizaciones?select=%2A "HTTP/2 200 OK"
[2025-08-06T23:26:54.283+0000] {logging_mixin.py:188} INFO - 
 ----------------------
data=[] count=None
[2025-08-06T23:26:54.285+0000] {python.py:201} INFO - Done. Returned value was: cargaicremental
[2025-08-06T23:26:54.295+0000] {branch.py:35} INFO - Branch into cargaicremental
[2025-08-06T23:26:54.300+0000] {skipmixin.py:178} INFO - Following branch cargaicremental
[2025-08-06T23:26:54.335+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 233, in execute
    return self.do_branch(context, super().execute(context))
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/branch.py", line 36, in do_branch
    self.skip_all_except(context["ti"], branches_to_execute)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/skipmixin.py", line 213, in skip_all_except
    raise AirflowException(
airflow.exceptions.AirflowException: 'branch_task_ids' must contain only valid task_ids. Invalid tasks found: {'cargaicremental'}.
[2025-08-06T23:26:54.347+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=Ejercicio2, task_id=Inicio, execution_date=20250806T232645, start_date=20250806T232651, end_date=20250806T232654
[2025-08-06T23:26:54.391+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 285 for task Inicio ('branch_task_ids' must contain only valid task_ids. Invalid tasks found: {'cargaicremental'}.; 4727)
[2025-08-06T23:26:54.446+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-08-06T23:26:54.545+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
